#pragma once

#include <vector>
#include <algorithm>
#include <iostream>
#include <string>


using namespace std;


class Continent
{


public : 


	Continent() {
		
			//vire doublons 
			sort(Europe.begin(), Europe.end());
			Europe.erase(unique(Europe.begin(), Europe.end()), Europe.end());

			sort(Africa.begin(), Africa.end());
			Africa.erase(unique(Africa.begin(), Africa.end()), Africa.end());

			sort(Oceania.begin(), Oceania.end());
			Oceania.erase(unique(Oceania.begin(), Oceania.end()), Oceania.end());

			sort(Asia.begin(), Asia.end());
			Asia.erase(unique(Asia.begin(), Asia.end()), Asia.end());

			sort(South_America.begin(), South_America.end());
			South_America.erase(unique(South_America.begin(), South_America.end()), South_America.end());

			sort(North_America.begin(), North_America.end());
			North_America.erase(unique(North_America.begin(), North_America.end()), North_America.end());
		
	}

	inline vector<std::string> GetContinentByName(std::string Continent_Name) {


		if (Continent_Name == "Europe") {
			return Europe;
		}
		else {
			if (Continent_Name == "Africa") {
				return Africa;
			}
			else
			{
				if (Continent_Name == "Oceania") {
					return Oceania;
				}
				else {
					if (Continent_Name == "Asia") {
						return Asia;
					}
					else {
						if (Continent_Name == "South America") {
							return South_America;
						}
						else {
							if (Continent_Name == "North America") {
								return North_America;
								
							}
							else {
								return World;
							}

						}
					}
				}
			}
		}
		
	
	}





protected:






	vector<std::string> Europe{ "Russian Federation",
							"Ukraine",
							"France",
							"Spain",
							"Sweden",
							"Norway",
							"Germany",
							"Finland",
							"Poland",
							"Italy",
							"United Kingdom",
							"Romania",
							"Belarus",
							"Kazakhstan",
							"Greece",
							"Bulgaria",
							"Iceland",
							"Hungary",
							"Portugal",
							"Austria",
							"Czech Republic",
							"Serbia",
							"Ireland",
							"Lithuania",
							"Latvia",
							"Croatia",
							"Bosnia and Herzegovina",
							"Slovakia",
							"Estonia",
							"Denmark",
							"Switzerland",
							"Netherlands",
							"Moldova",
							"Belgium",
							"Armenia",
							"Albania",
							" North Macedonia",
							"Turkey",
							"Slovenia",
							"Montenegro",
							"Kosovo",
							"Cyprus",
							"Azerbaijan",
							"Ukraine",
							"France",
							"Spain",
							"Sweden",
							"Norway",
							"Germany",
							"Finland",
							"Poland",
							"Italy",
							"United Kingdom",
							"Romania",
							"Belarus",
							"Kazakhstan",
							"Greece",
							"Bulgaria",
							"Iceland",
							"Hungary",
							"Portugal",
							"Austria",
							"Czech Republic",
							"Serbia",
							"Ireland",
							"Lithuania",
							"Latviav",
							"Croatia",
							"Bosnia and Herzegovina",
							"Slovakia",
							"Estonia",
							"Denmark",
							"Switzerland",
							"Netherlands",
							"Moldova",
							"Belgium",
							"Armenia",
							"Albania",
							" North Macedonia",
							"Turkey",
							"Slovenia",
							"Montenegro",
							"Kosovo",
							"Cyprus",
							"Azerbaijan",
							"Luxembourg",
							"Georgia",
							"Andorra",
							"Malta",
							"Liechtenstein",
							"San Marino",
							"Monaco",
							"Vatican City",
							"Georgia",
							"Andorra",
							"Malta",
							"Liechtenstein",
							"San Marino",
							"Monaco",
							"Vatican CityRussia",
							"Ukraine",
							"France",
							"Spain",
							"Sweden",
							"Norway",
							"Germany",
							"Finland",
							"Poland",
							"Italy",
							"United Kingdom",
							"Romania",
							"Belarus",
							"Kazakhstan",
							"Greece",
							"Bulgaria",
							"Iceland",
							"Hungary",
							"Portugal",
							"Austria",
							"Czech Republic",
							"Serbia",
							"Ireland",
							"Lithuania",
							"Latvia",
							"Croatia",
							"Bosnia and Herzegovina",
							"Slovakia",
							"Estonia",
							"Denmark",
							"Switzerland",
							"Netherlands",
							"Moldova",
							"Belgium",
							"Armenia",
							"Albania",
							"North Macedonia",
							"Turkey",
							"Slovenia",
							"Montenegro",
							"Kosovo",
							"Cyprus",
							"Azerbaijan",
							"Ukraine",
							"France",
							"Spain",
							"Sweden",
							"Norway",
							"Germany",
							"Finland",
							"Poland",
							"Italy",
							"United Kingdom",
							"Romania",
							"Belarus",
							"Kazakhstan",
							"Greece",
							"Bulgaria",
							"Iceland",
							"Hungary",
							"Portugal",
							"Austria",
							"Czech Republic",
							"Serbia",
							"Ireland",
							"Lithuania",
							"Latvia",
							"Croatia",
							"Bosnia and Herzegovina",
							"Slovakia",
							"Estonia",
							"Denmark",
							"Switzerland",
							"Netherlands",
							"Moldova",
							"Belgium",
							"Armenia",
							"Albania",
							" North Macedonia",
							"Turkey",
							"Slovenia",
							"Montenegro",
							"Kosovo",
							"Cyprus",
							"Azerbaijan",
							"Luxembourg",
							"Georgia",
							"Andorra",
							"Malta",
							"Liechtenstein",
							"San Marino",
							"Monaco",
							"Vatican City",
							"Georgia",
							"Andorra",
							"Malta",
							"Liechtenstein",
							"San Marino",
							"Monaco",
							"Vatican City"
};





	vector <std::string> Oceania{
							"Australia",
							"Papua New Guinea",
							"New Zealand",
							"Fiji",
							"Solomon Islands",
							"Vanuatu",
							"New Caledonia",
							"French Polynesia",
							"Samoa",
							"Guam",
							"Kiribati",
							"Federated States of Micronesia",
							"Tonga",
							"American Samoa",
							"Northern Mariana Islands",
							"Marshall Islands",
							"Palau",
							"Cook Islands",
							"Wallis and Futuna",
							"Tuvalu",
							"Nauru",
							"Norfolk Island",
							"Niue",
							"Tokelau",
							"Pitcairn IslandsAustralia",
							"Papua New Guinea",
							"New Zealand",
							"Fiji",
							"Solomon Islands",
							"Vanuatu",
							"New Caledonia",
							"French Polynesia",
							"Samoa",
							"Guam",
							"Kiribati",
							"Federated States of Micronesia",
							"Tonga",
							"American Samoa",
							"Northern Mariana Islands",
							"Marshall Islands",
							"Palau",
							"Cook Islands",
							"Wallis and Futuna",
							"Tuvalu",
							"Nauru",
							"Norfolk Island",
							"Niue",
							"Tokelau",
							"Pitcairn Islands"
};

	vector<std::string> Asia{
"Russian Federation",
"China",
"India",
"Kazakhstan",
"Saudi Arabia",
"Iran",
"Mongolia",
"Indonesia",
"Pakistan",
"Turkey",
"Myanmar",
"Afghanistan",
"Yemen",
"Thailand",
"Turkmenistan",
"Uzbekistan",
"Iraq",
"Japan",
"Vietnam",
"Malaysia",
"Oman",
"Philippines",
"Laos",
"Kyrgyzstan",
"Syria",
"Cambodia",
"Bangladesh",
"Nepal",
"Tajikistan",
"Jordan",
"Azerbaijan",
"United Arab Emirates",
"Georgia",
"Sri Lanka",
"Egypt",
"Bhutan",
"Taiwan",
"Armenia",
"Kuwait",
"Timor-Leste",
"Qatar",
"Lebanon",
"Israel",
"Palestine",
"Brunei",
"Singapore",
"Bahrain",
"Maldives",
"China",
"India",
"Kazakhstan",
"Saudi Arabia",
"Iran",
"Mongolia",
"Indonesia",
"Pakistan",
"Turkey",
"Myanmar",
"Afghanistan",
"Yemen",
"Thailand",
"Turkmenistan",
"Uzbekistan",
"Iraq",
"Japan",
"Vietnam",
"Malaysia",
"Oman",
"Philippines",
"Laos",
"Kyrgyzstan",
"Syria",
"Cambodia",
"Bangladesh",
"Nepal",
"Tajikistan",
"North Korea",
"South Korea",
"Jordanv",
"Azerbaijan",
"United Arab Emirates",
"Georgia",
"Sri Lanka",
"Egypt",
"Bhutan",
"Taiwan",
"Armenia",
"Kuwait",
"Timor-Leste",
"Qatar",
"Lebanon",
"Israel",
"Palestine",
"Brunei",
"Singapore",
"Bahrain",
"Maldives"};


	vector<std::string> South_America{ "Brazil",
                                       "Colombia",
                                       "Argentina",
                                       "Peru",
                                       "Venezuela-RB",
                                       "Chile",
                                       "Ecuador",
                                       "Bolivia",
                                       "Paraguay",
                                       "Uruguay",
                                       "Guyana",
                                       "Suriname",
                                       "French Guiana",
                                       "Falkland IslandsBrazil",
                                       "Colombia",
                                       "Argentina",
                                       "Peru",
                                       "Chile",
                                       "Ecuador",
                                       "Bolivia",
                                       "Paraguay",
                                       "Uruguay",
                                       "Guyana",
                                       "Suriname",
                                       "French Guiana",
                                       "Falkland Islands"};


	vector<std::string> North_America{ "United States",
                                       "Mexico",
                                       "Canada",
                                       "Guatemala",
                                       "Cuba",
                                       "Haiti",
                                       "Dominican Republic",
                                       "Honduras",
                                       "El Salvador",
                                       "Nicaragua",
                                       "Costa Rica",
                                       "Panama",
                                       "Puerto Rico",
                                       "Jamaica",
                                       "Trinidad and Tobago",
                                       "Guadeloupe",
                                       "Martinique",
                                       "Bahamas",
                                       "Belize",
                                       "Barbados",
                                       "Saint Lucia",
                                       "Saint Vincent and the Grenadines",
                                       "U.S. Virgin Islands",
                                       "Grenada",
                                       "Antigua and Barbuda",
                                       "Dominica",
                                       "Bermuda",
                                       "Cayman Islands",
                                       "Greenlandv",
                                       "Saint Kitts and Nevis",
                                       "Sint Maarten",
                                       "Turks and Caicos Islandsv",
                                       "Saint Martin",
                                       "British Virgin Islands",
                                       "Caribbean Netherlands",
                                       "Anguilla",
                                       "Saint Barthélemy",
                                       "Saint Pierre and Miquelon",
                                       "Montserrat",
                                       "United States",
                                       "Mexico",
                                       "Canada",
                                       "Guatemala",
                                       "Cuba",
                                       "Haiti",
                                       "Dominican Republic",
                                       "Honduras",
                                       "El Salvador",
                                       "Nicaragua",
                                       "Costa Rica",
                                       "Panama",
                                       "Puerto Rico",
                                       "Jamaica",
                                       "Trinidad and Tobago",
                                       "Guadeloupe",
                                       "Martinique",
                                       "Bahamas",
                                       "Belize",
                                       "Barbados",
                                       "Saint Lucia",
                                       "Saint Vincent and the Grenadines",
                                       "U.S. Virgin Islands",
                                       "Grenada",
                                       "Antigua and Barbuda",
                                       "Dominica",
                                       "Bermuda",
                                       "Cayman Islands",
                                       "Greenland",
                                       "Saint Kitts and Nevis",
                                       "Sint Maarten",
                                       "Turks and Caicos Islands",
                                       "Saint Martin",
                                       "British Virgin Islands",
                                       "Caribbean Netherlands",
                                       "Anguilla",
                                       "Saint Barthélemy",
                                       "Saint Pierre and Miquelon",
                                       "Montserrat"};



	vector<std::string> Africa{ "Nigeria",
							"Ethiopia",
							"Egypt",
							"Democratic Republic of the Congo",
							"South Africa",
							"Tanzania",
							"Kenya",
							"Sudan",
							"Algeria",
							"Uganda",
							"Morocco",
							"Mozambique",
							"Ghana",
							"Angola",
							"Ivory Coast",
							"Madagascar",
							"Cameroon",
							"Niger",
							"Burkina Faso",
							" Mali",
							"Malawi",
							"Zambia",
							"Somalia",
							"Senegal",
							"Chad",
							"Zimbabwe",
							"Rwanda",
							"Tunisia",
							"Guinea",
							"Benin",
							"Burundi",
							"South Sudan",
							"Togo",
							"Eritrea",
							"Sierra Leone",
							"Libya",
							"Republic of the Congo",
							"Central African Republic",
							"Liberia",
							"Mauritania",
							"Namibia",
							"Botswana",
							"Lesotho",
							"Gambia",
							"Gabon",
							"Guinea-Bissau",
							"Mauritius",
							"Equatorial Guinea",
							"Eswatini",
							"Djibouti",
							"Comoros",
							"Cape Verde",
							"Western Sahara",
							"Seychelles" };






	vector<std::string> World{
			"Afghanistan",
			"Angola",
			"Albania",
			"Andorra",
			"United Arab Emirates",
			"Arab World",
			"Argentina",
			"American Samoa",
			"Aruba",
			"Armenia",
			"Antigua and Barbuda",
			"Belgium",
			"Azerbaijan",
			"Burundi",
			"Burkina Faso",
			"Benin",
			"Bangladesh",
			"Austria",
			"Australia",
			"Bermuda",
			"Belarus",
			"Belize",
			"Barbados",
			"Brazil",
			"Bahrain",
			"Brunei Darussalam",
			"Bosnia and Herzegovina",
			"Bahamas",
			"Bolivia",
			"Bulgaria",
			"Chile",
			"China",
			"Cote d'Ivoire",
			"Cameroon",
			"Congo-Dem. Rep.",
			"Congo-Rep.",
			"Colombia",
			"Comoros",
			"Cabo Verde",
			"Costa Rica",
			"Central Europe and the Baltics",
			"Botswana",
			"Switzerland",
			"Channel Islands",
			"Bhutan",
			"Central African Republic",
			"Canada",
			"Djibouti",
			"Dominica",
			"Denmark",
			"Dominican Republic",
			"Algeria",
			"East Asia & Pacific (excluding high income)",
			"Early-demographic dividend",
			"East Asia & Pacific",
			"Europe & Central Asia (excluding high income)",
			"Europe & Central Asia",
			"Germany",
			"Czech Republic",
			"Egypt",
			"Cyprus",
			"Cayman Islands",
			"Curacao",
			"Ecuador",
			"Caribbean small states",
			"Euro area",
			"Cuba",
			"Fiji",
			"France",
			"France",
			"Faroe Islands",
			"Micronesia-Fed. Sts.",
			"Gabon",
			"United Kingdom",
			"Georgia",
			"Ghana",
			"Gibraltar",
			"Guinea",
			"Fragile and conflict affected situations",
			"Finland",
			"Spain",
			"European Union",
			"Ethiopia",
			"Eritrea",
			"Estonia",
			"Guatemala",
			"Greece",
			"Gambia",
			"Hong Kong SAR-China",
			"High income",
			"Guinea-Bissau",
			"Heavily indebted poor countries (HIPC)",
			"Honduras",
			"Croatia",
			"Grenada",
			"IBRD only",
			"Hungary",
			"Guyana",
			"Haiti",
			"Equatorial Guinea",
			"Greenland",
			"India",
			"Not classified",
			"Ireland",
			"Iran",
			"Iraq",
			"Iceland",
			"Israel",
			"Italy",
			"Jamaica",
			"IDA total",
			"IDA only",
			"IDA blend",
			"Jordan",
			"Guam",
			"IDA & IBRD total",
			"Indonesia",
			"Isle of Man",
			"Korea-Rep.",
			"Kuwait",
			"Latin America & Caribbean (excluding high income)",
			"Lao PDR",
			"Lebanon",
			"Liberia",
			"Libya",
			"St. Lucia",
			"Latin America & Caribbean",
			"Least developed countries: UN classification",
			"St. Kitts and Nevis",
			"Kiribati",
			"Kazakhstan",
			"Cambodia",
			"Japan",
			"Kenya",
			"Kyrgyz Republic",
			"Sri Lanka",
			"Lesotho",
			"Lithuania",
			"Liechtenstein",
			"St. Martin (French part)",
			"Morocco",
			"Monaco",
			"Moldova",
			"Madagascar",
			"Maldives",
			"Low income",
			"Mexico",
			"Middle East & North Africa",
			"Marshall Islands",
			"Luxembourg",
			"Lower middle income",
			"Macao SAR-China",
			"Late-demographic dividend",
			"Low & middle income",
			"Latvia",
			"North Macedonia",
			"Middle income",
			"Malta",
			"Mali",
			"Middle East & North Africa (excluding high income)",
			"Myanmar",
			"Mongolia",
			"Montenegro",
			"Northern Mariana Islands",
			"Mozambique",
			"Mauritania",
			"North America",
			"New Caledonia",
			"Malawi",
			"Nicaragua",
			"Namibia",
			"Netherlands",
			"Norway",
			"Niger",
			"Nepal",
			"Nauru",
			"OECD members",
			"New Zealand",
			"Oman",
			"Mauritius",
			"Malaysia",
			"Nigeria",
			"Poland",
			"Pre-demographic dividend",
			"Puerto Rico",
			"Korea-Dem. People’s Rep.",
			"Portugal",
			"Paraguay",
			"West Bank and Gaza",
			"Pacific island small states",
			"Post-demographic dividend",
			"French Polynesia",
			"Peru",
			"Philippines",
			"Palau",
			"Pakistan",
			"Papua New Guinea",
			"Panama",
			"Other small states",
			"Russian Federation",
			"Qatar",
			"Romania",
			"South Asia",
			"Rwanda",
			"Sudan",
			"Saudi Arabia",
			"Solomon Islands",
			"Senegal",
			"Singapore",
			"San Marino",
			"Sierra Leone",
			"El Salvador",
			"Sub-Saharan Africa (excluding high income)",
			"Somalia",
			"Serbia",
			"Sao Tome and Principe",
			"South Sudan",
			"Sint Maarten (Dutch part)",
			"Seychelles",
			"Sub-Saharan Africa",
			"Turks and Caicos Islands",
			"Chad",
			"East Asia & Pacific (IDA & IBRD countries)",
			"Slovenia",
			"Small states",
			"Eswatini",
			"Suriname",
			"Syrian Arab Republic",
			"Slovak Republic",
			"Sweden",
			"Middle East & North Africa (IDA & IBRD countries)",
			"Tonga",
			"South Asia (IDA & IBRD)",
			"Sub-Saharan Africa (IDA & IBRD countries)",
			"Trinidad and Tobago",
			"Tunisia",
			"Turkey",
			"Tuvalu",
			"Tanzania",
			"Uganda",
			"Ukraine",
			"Upper middle income",
			"Uruguay",
			"United States",
			"Uzbekistan",
			"Tajikistan",
			"Latin America & the Caribbean (IDA & IBRD countries)",
			"Timor-Leste",
			"Togo",
			"St. Vincent and the Grenadines",
			"Venezuela-RB",
			"British Virgin Islands",
			"Europe & Central Asia (IDA & IBRD countries)",
			"Thailand",
			"Turkmenistan",
			"Vietnam",
			"Virgin Islands (U.S.)",
			"Samoa",
			"Kosovo",
			"Yemen",
			"Vanuatu",
			"South Africa",
			"Zambia",
			"World",
			"Zimbabwe"
	};









};

